### ISSUE TITLE
Crash when instantiating `SimplifiedRegexCharacterClass` with certain case-insensitive ranges

### ISSUE THREAD

**Issue by karim-ouerghemmi-sonarsource** [SonarSource/sonar-analyzer-commons#156]
When instantiating `SimplifiedRegexCharacterClass` with a valid range between an upper-case and a lower-case letter (e.g., `Z-a`), and having the case-insensitive flag set, a crash occurs. This can be reproduced with the following test:
```java
@Test
void name() {
  FlagSet flagSet = new FlagSet(Pattern.CASE_INSENSITIVE);
  CharacterClassTree characterClassTree = (CharacterClassTree) parseRegex("[Z-a]", flagSet).getResult();
  SimplifiedRegexCharacterClass characterClass = new SimplifiedRegexCharacterClass(characterClassTree);
}
```

Stack trace:
```
java.lang.IllegalArgumentException: fromKey > toKey

	at java.base/java.util.TreeMap$NavigableSubMap.<init>(TreeMap.java:1365)
	at java.base/java.util.TreeMap$AscendingSubMap.<init>(TreeMap.java:1852)
	at java.base/java.util.TreeMap.subMap(TreeMap.java:910)
	at org.sonar.java.checks.helpers.SimplifiedRegexCharacterClass.addRange(SimplifiedRegexCharacterClass.java:201)
	at org.sonar.java.checks.helpers.SimplifiedRegexCharacterClass$Builder.addRange(SimplifiedRegexCharacterClass.java:361)
```
This was noticed when the rule `DuplicatesInCharacterClassCheck` using this class crashed on the regex `(?iu)[^0-9a-zÀ-ÖÙ-öù-ÿœ\s]`. A simpler regex that would crash the rule too is `(?i)[Z-ax]`.

**Comment by karim-ouerghemmi-sonarsource** [comment]
Once this is fixed, the temporary exception catching introduced in SonarPHP here https://github.com/SonarSource/sonar-php/pull/842/files should be removed.
