### ISSUE TITLE
Still observe deadlock on ProgressReport

### ISSUE THREAD

**Issue by tina-chen** [SonarSource/sonar-analyzer-commons#190]
Even though there's a previous fix [#152](https://github.com/SonarSource/sonar-analyzer-commons/pull/152), I still observe deadlock with Java custom rule plugin against LTS 8.9. 

I modified the pom.xml to use the latest ProgressReport, but still got the deadlock error from time to time:

        <dependency>
            <groupId>org.sonarsource.java</groupId>
            <artifactId>sonar-java-plugin</artifactId>
            <type>sonar-plugin</type>
            <version>6.15.1.26025</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.sonarsource.analyzer-commons</groupId>
                    <artifactId>sonar-analyzer-commons</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.sonarsource.analyzer-commons</groupId>
            <artifactId>sonar-analyzer-commons</artifactId>
            <version>1.22.0.848</version>
        </dependency>

Error:
"main" #1 prio=5 os_prio=0 cpu=5890.63ms elapsed=238.90s tid=0x000001791f677800 nid=0x3cb0 in Object.wait()  [0x0000005d7fdfc000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@11.0.11/Native Method)
        - waiting on <0x0000000709b8fcf8> (a java.lang.Thread)
        at java.lang.Thread.join(java.base@11.0.11/Thread.java:1300)
        - waiting to re-lock in wait() <0x0000000709b8fcf8> (a java.lang.Thread)
        at java.lang.Thread.join(java.base@11.0.11/Thread.java:1375)
        at org.sonarsource.analyzer.commons.ProgressReport.join(ProgressReport.java:116)
        at org.sonarsource.analyzer.commons.ProgressReport.stop(ProgressReport.java:106)
        - locked <0x0000000709b8fca8> (a org.sonarsource.analyzer.commons.ProgressReport)
        at org.sonar.java.ast.JavaAstScanner.scan(JavaAstScanner.java:86)
        at org.sonar.java.checks.verifier.InternalCheckVerifier.verifyAll(InternalCheckVerifier.java:218)
        at org.sonar.java.checks.verifier.InternalCheckVerifier.verifyIssues(InternalCheckVerifier.java:166)

**Comment by tina-chen** [comment]
Any update on this one?  My plugin from time to time failed unit tests due to this issue.  Thanks.

**Comment by Wohops** [comment]
Imported to Jira: [ACOMMONS-2](https://sonarsource.atlassian.net/browse/ACOMMONS-2)
