### ISSUE TITLE
Fix classloader issue in SonarLint IntelliJ for Nashorn-based JSON parser

### ISSUE THREAD

**Issue by pynicolas** [SonarSource/sonar-analyzer-commons#43]
We can't embed an analyzer which uses `RuleMetadataLoader(String resourceFolder, String defaultProfilePath)` inside SonarLint for IntelliJ. If we do, then IntelliJ fails to start with an exception like:
```
Caused by: java.lang.ClassCastException: jdk.nashorn.api.scripting.ScriptObjectMirror cannot be cast to jdk.nashorn.api.scripting.JSObject
        at org.sonarsource.analyzer.commons.JsonParser.<init>(JsonParser.java:36)
        at org.sonarsource.analyzer.commons.ProfileDefinitionReader.loadActiveKeysFromJsonProfile(ProfileDefinitionReader.java:59)
        at org.sonarsource.analyzer.commons.RuleMetadataLoader.<init>(RuleMetadataLoader.java:60)
        at org.sonar.plugins.python.PythonRuleRepository.getRuleMetadataLoader(PythonRuleRepository.java:56)
        at org.sonar.plugins.python.PythonRuleRepository.define(PythonRuleRepository.java:46)
```

**Comment by saberduck** [comment]
I think we should cast to `java.util.Map`  that should solve the issue. Adding the dependency just because of this is a bad idea
